Frontend recommendation bundle
lavaloop-official/GovLearn pull request #22
Opened 2023-11-20 15:05 UTC by lavaloop-official

Added category entity
Added endpoint for frontend recommendation bundle

@Mrjulss Bitte einmal auf Sinnhaftigkeit prüfen.

2023-11-21 10:26 UTC, Mrjulss requested changes
Die Logik ist so wie wir das besprochen haben.
So wie ich das sehe suchst du
- nach den Kategorien mit den meisten Tags des Users
- sortierst die absteigend 
- lässt die Recommendation-Logik über alle Kurse der Kategorien durchlaufen
- fügst die dem category element hinzu
oder?

Änderungen:
Ich denke in featured sollten wir fürs erste einfach die besten 5 recommendations von allen Kursen ausgeben
und es wäre wahrscheinlich hilfreich wenn man das limit der Kategorien im Endpunkt mitgibt statt starr 4 zu machen, da man das ja vlt. an anderer stelle auch nutzen will
@comlit was sagst du dazu?

2023-11-21 10:35 UTC, comlit commented
@Mrjulss einfach die 5 besten für featured halt ich für sehr sinnvoll. aber die categories würd ich glaub ich nicht limiten. würde ich glaub ich einfach dynamisch bestimmen im backend. z.B. einfach so viele bis die für den Nutzer irrelevant werden

2023-11-21 14:02 UTC, Mrjulss commented
> @Mrjulss einfach die 5 besten für featured halt ich für sehr sinnvoll. aber die categories würd ich glaub ich nicht limiten. würde ich glaub ich einfach dynamisch bestimmen im backend. z.B. einfach so viele bis die für den Nutzer irrelevant werden

ist jetzt nicht einfach zu sagen wann die irrelevant werden, außerdem kann die response dann auch sehr groß werden ohne limitierung, hätte gedacht das front-end lässt sich leichter gestalten wenn man eine fixe anzahl an categories vorraussetzen kann

2023-11-21 14:09 UTC, comlit commented
> > @Mrjulss einfach die 5 besten für featured halt ich für sehr sinnvoll. aber die categories würd ich glaub ich nicht limiten. würde ich glaub ich einfach dynamisch bestimmen im backend. z.B. einfach so viele bis die für den Nutzer irrelevant werden
> 
> ist jetzt nicht einfach zu sagen wann die irrelevant werden, außerdem kann die response dann auch sehr groß werden ohne limitierung, hätte gedacht das front-end lässt sich leichter gestalten wenn man eine fixe anzahl an categories vorraussetzen kann

Ja ich check was du meinst. Hard Limit ist wahrscheinlich am einfachsten. Würde dann aber sagen das der request einfach ~7 Stück zurück gibt und fertig. Das Frontend ist so dynamisch gestaltet das das eigentlich egal ist wie viel da kommt. Und dann kann man ja nochmal später über dynamisches nachladen/nachrequesten quatschen.

2023-11-22 13:57 UTC, comlit approved these changes
hab die categories auf 6 gelimited und einfach basierend auf dem bestehenden algorithmus die featured geholt. denke das sollte passen

2023-11-27 16:46 UTC, Mrjulss approved these changes

2023-11-27 17:28 UTC, comlit commented
na dann viel spaß beim merge conflict resolven 🙃

2023-11-28 10:49 UTC, merged