Feature/search with options
lavaloop-official/GovLearn pull request #47
Opened 2023-12-12 20:11 UTC by Paramian

Added support to filter for format, skilllevel, cost and provider.
Added endpoint to retrieve all provider

Next to dos:
- cleanup database to support more options
- extent search

2023-12-13 19:47 UTC, comlit requested changes
kosten ist weird:
-wenn request mit kosten true dann werden nur kurse zurückgegeben wo costfree=false
-die checkbox im frontend ist aber mit "kostenlos" gelabelt?

2023-12-17 14:02 UTC, Paramian commented
> kosten ist weird: -wenn request mit kosten true dann werden nur kurse zurückgegeben wo costfree=false -die checkbox im frontend ist aber mit "kostenlos" gelabelt?

ja das ist leider vom naming her in der Entity schon so gegeben :/ ich ändere das im WsTo auf kostenlos. Dann sollte das soweit wieder einheitlich sein

2023-12-17 14:46 UTC, comlit approved these changes
nice das passt das ja jetzt. gute arbeit. man muss dann aber wahrscheinlich einmal die db neu aufsetzen lokal oder?

2023-12-17 15:27 UTC, Paramian commented
Ne, das passt alles soweit, weil die Entität gleich bleibt:)

2023-12-17 15:38 UTC, comlit commented
Ok check und wie ist das im Frontend? Müssen wir da denn dann Namen ändern?

2023-12-17 15:40 UTC, Paramian commented
Habe ich schon entsprechend angepasst ^^ der PR ist auch schon gemerged

2023-12-17 15:48 UTC, comlit commented
Das ist ja traumhaft 👍🏻

2023-12-19 09:59 UTC, merged