Feature/groups
lavaloop-official/GovLearn pull request #51
Opened 2023-12-17 14:01 UTC by lavaloop-official

An notion ticket orientiert: https://www.notion.so/Sprint-Backlog-2bd2ad1aa88b4ce4baa17bec9903c2ef?p=406ec87bb6ac47549826a5f9177dec1f&pm=s

2023-12-17 15:06 UTC, lavaloop-official commented
Und auch gerne direkt mergen

2023-12-19 14:22 UTC, Paramian requested changes

2023-12-19 14:22 UTC, Paramian commented on govlearn-api/src/main/java/com/unimuenster/govlearnapi/group/controller/GroupMembersController.java
> +    @GetMapping("/{groupId}")
Beide Get Endpunkte haben die selbe Route

2023-12-19 14:25 UTC, Paramian requested changes

2023-12-19 14:25 UTC, Paramian commented on govlearn-api/src/main/java/com/unimuenster/govlearnapi/group/controller/GroupMembersController.java
> +    @PutMapping()
Warum Put? :) => Post

2023-12-19 14:25 UTC, Paramian commented on govlearn-api/src/main/java/com/unimuenster/govlearnapi/group/controller/GroupContentController.java
> +    @PutMapping()
Warum put? => post

2023-12-19 14:29 UTC, Paramian requested changes

2023-12-19 14:29 UTC, Paramian commented on govlearn-api/src/main/java/com/unimuenster/govlearnapi/group/controller/GroupContentController.java
> +    @GetMapping("/{groupId}")
Wirft internal server error, wenn user nicht in der Gruppe ist:
java.lang.RuntimeException: User is not in group

2023-12-19 14:39 UTC, Paramian commented
Das Frontend braucht folgende Endpunkte:
- Adminbereich:
    - Als Admin benötige ich alle Kurse von allen Gruppenmitgliedern
    - Alle Gruppenmitglieder müssen mit ihrer entsprechenden Rolle zurückgegeben werden
    - Gruppenmitgliedern kann ein Kurs zugewiesen werden
    - Allen Gruppenmitgliedern kann ein Kurs zugewiesen werden
    - Beschreibung und Titel der Gruppe kann geändert werden
    - Kursinformationen zurückgeben
    - Gruppenmitglieder können in Gruppen eingeladen werden ohne diese direkt zur Gruppe hinzuzufügen (Jeder User muss eine Einladung annehmen)
- Memberbereich
    - Kursinformationen zurückgeben
    - Alle Gruppenmitglieder mit ihren Rollen zurückgeben
    - Alle zu bearbeitenden Kurse zurückgeben
    - Alle erledigten Kurse zurückgeben
- Allgemein
    - Alle Gruppenmitgliedschaften zurückgeben mit der jeweiligen Rolle in dieser Gruppe
    - Einladungen erhalten
    - Einladungen ablehnen oder annehmen

2023-12-27 16:28 UTC, lavaloop-official commented
Tests bitte fixen

2024-01-15 11:16 UTC, Paramian approved these changes

2024-01-15 19:35 UTC, Mrjulss approved these changes

2024-01-16 17:43 UTC, closed without merging