Extended user endpoint
lavaloop-official/GovLearn pull request #58
Opened 2024-01-01 15:39 UTC by Paramian

extended user by:
- reworking the change of username and usermail
- adding endpoint to change passwort

2024-01-01 21:36 UTC, Mrjulss requested changes
Gute Arbeit. Finde es nur etwas irritierend dass es den Update user und update user-password endpunkt gibt, vtl. sollte man Passwort ändern auch einfach über den update user endpunkt machen? Oder es etwas anders benennen. 
Wenn ich jetzt bei dem Update User endpunkt nur das Passwort ändere, kommt "keine Änderung gefunden"

2024-01-03 11:51 UTC, Paramian commented
@Mrjulss das Problem mit dem Passwort ändern ist, dass ich noch einen weiteren Abgleich machen möchte, ob das Passwort das gleiche wie vorher ist. Mir ist leider kein anderer Weg eingefallen, wie ich alles intelligent in einen Endpunkt integrieren kann, weil man ja nicht jedes Mal sein Passwort ändern möchte

2024-01-03 11:53 UTC, Mrjulss commented
> @Mrjulss das Problem mit dem Passwort ändern ist, dass ich noch einen weiteren Abgleich machen möchte, ob das Passwort das gleiche wie vorher ist. Mir ist leider kein anderer Weg eingefallen, wie ich alles intelligent in einen Endpunkt integrieren kann, weil man ja nicht jedes Mal sein Passwort ändern möchte

dann vlt den anderen Endpunkt entsprechend updateNameOrEMail nennen, damit man das voneinander trennen kann

2024-01-03 15:34 UTC, Paramian commented
ist jetzt umbenannt :)

2024-01-03 16:16 UTC, Mrjulss approved these changes
lgtm!

2024-01-03 16:31 UTC, merged